### 需求
#### 1. 对代码结构侵入性低,不影响控制流.
如果我们要发起两个请求,并且  后一个请求依赖于第一个请求的结果,那么在处理异常时,要精细化处理异常,  
每个都try catch捕获,但是异步请求的结果在try 里面,在外层作用域无法获取到  
请求的结果,我们可以通过把变量定义到最外层,但这样子对代码控制流影响比较大;  
并且对类型系统也不友好;要不然就是统一处理异常,抛弃精细化;  
#### 2. 明确的异常数据结构
异常本身的数据结构并不明确,我们可以reject任意类型的数据,他们都是异常;  
所以我们要:  
1.自定义一个CustomeError,通过继承Error,但是需要包含更多我们需要的属性;  
2.将任意类型封装成CustomeError,  
3.通过Lint规则保证,代码中不抛出其他类型的错误;
#### 3. 为异常提供正常值 
有异常的时候,给他赋一个正常的值;例如读取配置文件,没有结果的时候,给他赋一个默认值;
#### 4. 显式忽略异常
交给全局异常捕获来处理,或者暂时不知道怎么处理,或者没有恰当的方式提示;  
并且中断之后代码的执行;  
#### 5.实现全局通用的异常处理UI  
一些异常直接抛出到最外层,统一由顶部通知等形式展示;



1. unwrap    解决需求4
成功返回data,失败throw Error  
```js
async () => {
 // 这里如果是异常,就直接throw了.这么写可以认为是显式忽略异常
 const data = (await fetch('/api')).unwrap()
 console.log(data) //如果出错,这句代码不会被执行
}
```
>由于 Result 类型本身是确定的，unwrap 也是一次显式的调用，所以这样的逻辑非常容易被静态分析工具检查出来。甚至我们可以通过将 Result 类型中声明的 unwrap 方法暂时注释，观察 Typescript 编译器报错的方式找出所有忽略异常的代码;

2. 接上,当出错时,下面的console不会打印,针对这一场景,设计expect方法;  
`用于捕获异常后,向外抛出一个自定义的异常;  `
```ts
interface Result<T>{
    unwrap():T|never  //这里是返回值吗
    expect(msg:stirng): T|never
}

async function fetch<T>(url:string) :Promise<Result<T>>{
    try{
        const data = awit originfetch(url);
        return {
            unwrap(){
                return data;
            },
            expect(){
                return data
            }
        }
    }catch(error){
        return {
            unwrap(){
                throw new Error();
            },
            expect(msg){
                throw new Error(msg)
            }
        }
    }
}
```
代码示例:  
```js
async ()=>{
    const data = (await fetch('api')).expect('this is specical error....';
    console.log(data))
}
```
`3.捕获异常后,对异常进行展示或记录,后续代码不继续执行`  
```ts
interface Result<T>{
    unwrap():T|never  //这里是返回值吗
    expect(msg:stirng): T|never
    match<U>(fn:Match<T,U>):U
}

interface Match<T,U>{
    ok:(val:T) => U
    err: (val:CustomError) => U
}
async function fetch<T>(url:string) :Promise<Result<T>>{
    try{
        const data = awit originfetch(url);
        return {
            unwrap(){
                return data;
            },
            expect(){
                return data
            }
        }
    }catch(error){
        return {
            unwrap(){
                throw new Error();
            },
            expect(msg){
                throw new Error(msg)
            }
        }
    }
}
```
// 不懂
对 Result 类型的值调用 match 时，我们需要实现：  
1.正常值作为参数传入 ok 方法，其返回值作为 match 的最终返回值。  
2.异常值作为参数传入 err 方法，并且 err 方法可以有返回值，返回时其值也会作为 match 的最终返回值。  
3.异步成功时只有 ok 方法会被调用，反之只有 err 方法会被调用。  
代码示例:  
```js
async () => {
 const data = (await fetch('/api')).match({
   ok: val => val,
   err: err => {
     printError(err);
     throw err;
   }
 });
 log(data);
}
```

`当出现异常时给对应调用返回一个正常值作为 fallback，后续代码继续执行`  
可以通过match实现;  
```js
async ()=>{
    const data = (await fetch('/api')).match({
        ok:val => val,
        err: err=>{
            reutrn 'data fallback to this stirng';
        }
    })
    log(data)
}
```
因为 err 方法在实现时接受一个返回值，所以如果我们希望在异常时给出一个 fallback 的正常值，并且继续执行代码，那么就不需要在 err 方法中 throw，而是 return 一个正常值。  
这种场景下，我们可能并不需要对异常值本身做特殊处理，所以提供一个更简洁的 API：unwrapOr， 以避免在这个场景下写过多的 match 模板代码。
#### 在interface Result中增加unwrapOr  
```js
export interface Result<T> {
 unwrap(): T | never;
 unwrapOr(optb: T): T;  // 新增
 expect(params: ErrorParams): T | never;
 match<U>(fn: Match<T, U>): U;
}
unwrapOr这个方法需要保证:请求正常时,返回数据.异常时,接受参数,返回该参数;  

async ()=>{
    const data = (await fetch('/api')).unwrapOr('fallback strings');
    console.log(data)
}
```


### 总结
有四个函数,
unwrap,不接受参数, 成功:数据,失败,认为是忽略异常.后续代码不执行  
unwrapOr,接受一个fallback,成功:数据,失败,返回fallback参数(比较简洁)  
match,接受一个对象,包含ok,err两个参数,成功时返回数据,失败时,err作为参数,可以打印err,throw异常.  
(用于捕获异常后,对异常进行展示,或者记录,后续代码不继续执行)  
expect,接受一个异常的描述(字符串),成功返回数据,失败,返回一个自定义异常的


###　自定义异常结构
CustomerError中需要添加一些属性,并且这个类还能封装不同类型的数据;  
```js
enum ErrorCode{
    GENETIC = 10000,
    NOT_FOUND,
    UNWRAP,
    SALMON_NOT_READY
}
const locale:REcord<number,string> = {
    100001:'未找到'
}
export class CustomError extends Error{
    public code:ErrorCode;
    public formattedMessage:string;
    constructor(code =ErrorCode.GENETIC,msg:stirng){
        super(msg);
        this.code = code;
        this.formattedMessage = locale[this.code] || this.message;
        // 这里处理参数
    }
}
```
#### Error message转换  
上面的CustomError的构造函数中的msg需要是个字符串.但是Promise reject时不限制类型;因此需要对未知的数据类型进行转换,尽可能保留信息.  
大概如下所示:  
```js
function isFuntion(val:unknow) :val is Function{
    return typeof val ==='functioln'
}
function normalize(msg:unknown):stirng{
    let _msg:string;
    if(msg isntance Error){
        _msg = msg.message;
    }else if(
        typeof msg ==='object' &&
        msg!==null &&
        msg.toString &&
        isFunction(msg.toStirng)
    ){
        _msg = msg.toStirng()
    }else if(
        typeof msg === 'string'
    ){
        _msg = msg;
    }else{
        _msg = 'Unknown error;
    }
    return _msg;
}
```
通过这一过程，我们可以在保证类型安全的情况下将未知异常转化为 error message。但需要注意，实际通过 UI 向用户展示异常时，`我们还是应该优先使用 error code 和 i18n 处理后的字符串。`

### 禁止抛出CustomError以外的异常
可以通过设置Lint规则,即ast,

### 全局通用的异常处理UI 




